<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE credits_data [
<!ELEMENT credits_data (credits, assets, licenses, others)>
<!ELEMENT credits (credit)*>
<!ELEMENT credit (#PCDATA)>
<!ELEMENT assets (asset)*>
<!ELEMENT asset (assetname, author, from, license, extra?)>
<!ELEMENT assetname (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT extra (#PCDATA)>
<!ELEMENT licenses (licensetext)*>
<!ELEMENT licensetext (#PCDATA)>
<!ELEMENT others (other)*>
<!ELEMENT other (#PCDATA)>
]>
<credits_data>
<!--
TextMeshPro newline: &lt;br&gt;
turns into <br> when read
-->
<credits>
<credit>
This game was developed for the 2024 Global Game Jam.
</credit>
<credit>
Gameplay design, Prototyping, and overall Unity implementation malarkey
by Rachel Lowe (11BelowStudio)
</credit>
<credit>
Additional unity implementation refinements and 3D modelling
by Yang (A Big Owl)
</credit>
<credit>
Sound effects
by jujubee0728
</credit>
<credit>
3D modelling
by Kobby6-lang
</credit>
<credit>
Concept art
by Moktar Ali
</credit>
<credit>
Music
by Matthew Harper (stringsandbows/Matthew Harper Music)
</credit>
</credits>
<assets>
<!--

For all the assets obtained from elsewhere:
Add the info about the asset name, who it's by,
where it's from, and what license it was distributed under
in here, within a '<asset>' element.


For example:

<asset>
<assetname>haha 'ass'et lmao</assetname>
<author>Joe Momma</author>
<from>https://en.wikipedia.org/wiki/Special:Random</from>
<license>MIT license</license>
<extra>An optional bit of supplementary data because reasons I guess :shrug:</extra>
</asset>
-->
<asset>
<assetname>Hairibar.Ragdoll</assetname>
<author>Aitor Iribar</author>
<from>https://github.com/hairibar/Hairibar.Ragdoll</from>
<license>MIT</license>
</asset>
<asset>
<assetname>Comic Neue (font)</assetname>
<author>Craig Rozynski et al</author>
<from>http://comicneue.com/</from>
<license>Open Font License v1.1</license>
</asset>
<asset>
<assetname>Unnamed collection of 115 animations</assetname>
<author>Northern Alberta Institute of Technology</author>
<from>https://globalgamejam.org/sponsor/northern-alberta-institute-technology-nait</from>
<license>Freeware</license>
</asset>
<asset>
<assetname>get-terrain-texture</assetname>
<author>LlamAcademy</author>
<from>https://github.com/llamacademy/get-terrain-texture</from>
<license>MIT license</license>
<extra>Uses a modified version of FootstepSoundPlayer.cs</extra>
</asset>

<asset>
<assetname>R07-40-Whoops, Whistles, Laughter.wav</assetname>
<author>craigsmith</author>
<from>https://freesound.org/people/craigsmith/sounds/480754/</from>
<license>CC0</license>
</asset>
<asset>
<assetname>Mocking Laughter</assetname>
<author>Apheo</author>
<from>https://freesound.org/people/Apheo/sounds/382906/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>ccc_laughter.wav</assetname>
<author>uair01</author>
<from>https://freesound.org/people/uair01/sounds/89286/</from>
<license>CC-BY-3.0</license>
</asset>

<asset>
<assetname>Hehehe - Laughter</assetname>
<author>vikuserro</author>
<from>https://freesound.org/people/vikuserro/sounds/341036/</from>
<license>CC-BY-4.0</license>
</asset>

<asset>
<assetname>Laughter.mp3</assetname>
<author>Topschool</author>
<from>https://freesound.org/people/Topschool/sounds/360466/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>Laughter.mp3</assetname>
<author>Topschool</author>
<from>https://freesound.org/people/Topschool/sounds/360466/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>live audience comedy show genuine laughter_moderate.wav</assetname>
<author>HowardV</author>
<from>https://freesound.org/people/HowardV/sounds/581528/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>cackle laugh.wav</assetname>
<author>ERH</author>
<from>https://freesound.org/people/ERH/sounds/30941/</from>
<license>CC-BY-4.0</license>
</asset>

<asset>
<assetname>pirate Arr! 2</assetname>
<author>JD_Brick_Productions</author>
<from>https://freesound.org/people/JD_Brick_Productions/sounds/476325/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>PirateMatt (1).wav</assetname>
<author>qalba4j</author>
<from>https://freesound.org/people/qalba4j/sounds/401931/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>01_hey.wav</assetname>
<author>wayneoutthere</author>
<from>https://freesound.org/people/wayneoutthere/sounds/353137/</from>
<license>CC0</license>
</asset>

<asset>
<assetname>04_Thats_Me_Treasure.wav</assetname>
<author>wayneoutthere</author>
<from>https://freesound.org/people/wayneoutthere/sounds/353134/</from>
<license>CC0</license>
</asset>
<!--
<asset>
<assetname>haha 'ass'et lmao</assetname>
<author>Joe Momma</author>
<from>https://en.wikipedia.org/wiki/Special:Random</from>
<license>MIT license</license>
<extra>An optional bit of supplementary data because reasons I guess :shrug:</extra>
</asset>
-->
</assets>
<licenses>
<!--
<licensetext>
words words words
</licensetext>
-->
<!--
For some licenses (such as the MIT license), there is a legal requirement
to include a copy of some of the license text in anything that uses the
code released under that license. So, for those sorts of licenses,
copy the legally mandatory text into a 'licensetext' element down here, as follows:

<licensetext>
Copyright © 2024 Joe Mamma

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the “Software”),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
</licensetext>
-->
<licensetext>
Haribar.Ragdoll

Copyright (c) 2020 Aitor Iribar

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
</licensetext>
<licensetext>
get-terrain-texture

Copyright (c) 2021 LlamAcademy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
</licensetext>
</licenses>
<others>
<!--
For other bits of credits that don't neatly fit in elsewhere.
-->
<other>
Developed using Unity 2022.3.18f1
</other>
<!--<other>
Loosely based on some totally real lost media featuring
Captain Feathersword from The Wiggles
</other>-->
</others>
</credits_data>